#! /usr/bin/env php

<?php

use Nobox\CloneCommand;
use Nobox\NewCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Nobox Laravel Generator', 2.0);

$app->add(new NewCommand(new GuzzleHttp\Client));
$app->add(new CloneCommand(new GuzzleHttp\Client));

$app->run();
