#! /usr/bin/env php

<?php

use Nobox\NewCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Nobox Laravel Generator', 1.5);

$app->add(new NewCommand(new GuzzleHttp\Client));

$app->run();
